---
title: "Data Wrangling 2"
subtitle : "Read From Web"
output: github_document
---

```{r setup}
library(tidyverse)
library(rvest)
library(httr)
```

## Scrape a Table
First table from the page:

read in the html:
```{r}
data_url <- "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html <- read_html(data_url)

drug_use_html
```
extract the table; focus on the first one

```{r}
tabl_marj <-
drug_use_html %>% 
    html_nodes(css = "table") %>% 
    first() %>% 
    html_table() %>% 
    slice(-1) %>% 
    as.tibble()
```

##Star Wars Movie Info

```{r}
swm_html <- 
  read_html("https://www.imdb.com/list/ls070150896/")
```

Grab elements that I want.

```{r}
title_vec <-
    swm_html %>% 
    html_nodes(css = ".lister-item-header a") %>% 
    html_text()

gross_rev_vec <-
    swm_html %>% 
    html_nodes(css = ".text-muted .ghost~ .text-muted+ span") %>% 
    html_text()

run_time_vec <- 
    swm_html %>% 
    html_nodes(css = ".runtime") %>% 
    html_text()

swm_df <- 
    tibble(
        title = title_vec, 
        gross_rev = gross_rev_vec,
        runtime = run_time_vec
    )
```

## Get some water data

This is coming from an API

```{r}
nyc_water <- 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content("parsed")

nyc_water_json <- 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>%
    content("text") %>% 
    jsonlite::fromJSON() %>% 
    as.tibble()

```

##BRFSS

Same process, different data.
```{r}
brfss_smart2010 <- 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>% 
  content("parsed")
```
## Some data aren't so nice

Let's look at Pokemon..

```{r}
pokemon_data <-
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()
pokemon_data$name
pokemon_data$height
pokemon_data$abilities
```
## Closing  thougts
Be reasonable
